### ISSUE TITLE
Milestone 0.4.0 Discussion 

### ISSUE THREAD

**Issue by fanminshi** [etcd-io/jetcd#516]
Let's discuss what we want to fix/add for 0.4.0 milestone/release. For instance, I want to add lead election API to jetcd.  We can list some tasks we can to finish.

## Add Higher Level APIs:
- [ ] Add leader election API https://github.com/etcd-io/jetcd/issues/408
- [ ] Sequencer API https://github.com/etcd-io/jetcd/issues/473

## Bug Fixes
TODO
## Documentation Improvement
- [ ] Add testing style guide https://github.com/etcd-io/jetcd/issues/506

## Testing Improvement
- [ ] Remove testNG  https://github.com/etcd-io/jetcd/issues/309
- [ ] Performance Testing https://github.com/etcd-io/jetcd/issues/367

## Misc
TODO

cc/ @lburgazzoli  @vorburger

**Comment by fanminshi** [comment]
also cc/ @MalcolmSanders If you are interested in helping out.

**Comment by zrss** [comment]
hi @fanminshi , is 0.4.0 release ?

**Comment by lburgazzoli** [comment]
ourtdated
